
import { Question } from './types';

export const QUESTIONS: Question[] = [
  {
    id: 1,
    unit: "Unit 1: My New School",
    question: "We usually ______ football in the school playground at break time.",
    options: ["play", "plays", "playing", "to play"],
    correctAnswer: 0,
    explanation: "Sử dụng thì Hiện tại đơn với chủ ngữ 'We' thì động từ giữ nguyên mẫu.",
  },
  {
    id: 2,
    unit: "Unit 1: My New School",
    question: "Listen! Someone ______ at the door.",
    options: ["knock", "knocks", "is knocking", "are knocking"],
    correctAnswer: 2,
    explanation: "Dấu hiệu 'Listen!' cho thấy hành động đang xảy ra, dùng thì Hiện tại tiếp diễn (am/is/are + V-ing).",
  },
  {
    id: 3,
    unit: "Unit 2: My House",
    question: "There ______ a big table and some chairs in the middle of the kitchen.",
    options: ["is", "are", "be", "am"],
    correctAnswer: 0,
    explanation: "Cấu trúc 'There is/are'. Vì danh từ đầu tiên sau đó là 'a big table' (số ít) nên dùng 'is'.",
  },
  {
    id: 4,
    unit: "Unit 2: My House",
    question: "The cat is ______ the chair and the table.",
    options: ["on", "at", "between", "under"],
    correctAnswer: 2,
    explanation: "'Between... and...' dùng để chỉ vị trí ở giữa hai vật.",
  },
  {
    id: 5,
    unit: "Unit 3: My Friends",
    question: "My friend has a ______ face and short black hair.",
    options: ["round", "fat", "long", "big"],
    correctAnswer: 0,
    explanation: "'Round face' (mặt tròn) là cụm từ miêu tả ngoại hình phổ biến trong sách giáo khoa.",
  },
  {
    id: 6,
    unit: "Unit 3: My Friends",
    question: "Mai is very ______. She always helps her friends with their homework.",
    options: ["hard-working", "kind", "creative", "confident"],
    correctAnswer: 1,
    explanation: "'Kind' (tốt bụng) phù hợp với việc luôn giúp đỡ bạn bè.",
  },
  {
    id: 7,
    unit: "Unit 4: My Neighbourhood",
    question: "The air in the city is ______ than the air in the countryside.",
    options: ["polluted", "more polluted", "the most polluted", "polluteder"],
    correctAnswer: 1,
    explanation: "Cấu trúc so sánh hơn với tính từ dài: 'more + adj + than'.",
  },
  {
    id: 8,
    unit: "Unit 4: My Neighbourhood",
    question: "Living in a city is ______ than living in the countryside.",
    options: ["noisy", "more noisy", "noisier", "most noisy"],
    correctAnswer: 2,
    explanation: "Tính từ ngắn kết thúc bằng 'y', khi so sánh hơn đổi 'y' thành 'i' rồi thêm 'er'.",
  },
  {
    id: 9,
    unit: "Unit 5: Natural Wonders",
    question: "Fansipan is the ______ mountain in Vietnam.",
    options: ["high", "higher", "highest", "the highest"],
    correctAnswer: 2,
    explanation: "Cấu trúc so sánh nhất với tính từ ngắn: 'the + adj + est'. (Lưu ý: trong câu đã có 'the' trước ô trống ở một số đề, ở đây ta chọn 'highest').",
  },
  {
    id: 10,
    unit: "Unit 5: Natural Wonders",
    question: "You ______ take a waterproof coat because it often rains there.",
    options: ["must", "mustn't", "shouldn't", "can't"],
    correctAnswer: 0,
    explanation: "'Must' dùng để chỉ sự cần thiết hoặc bắt buộc.",
  },
  {
    id: 11,
    unit: "Unit 6: Our Tet Holiday",
    question: "Students ______ behave well during Tet holiday.",
    options: ["should", "shouldn't", "mustn't", "can"],
    correctAnswer: 0,
    explanation: "'Should' dùng để đưa ra lời khuyên nên làm gì.",
  },
  {
    id: 12,
    unit: "Unit 6: Our Tet Holiday",
    question: "We don't have ______ milk left. Let's go and buy some.",
    options: ["any", "some", "a", "an"],
    correctAnswer: 0,
    explanation: "'Any' thường được dùng trong câu phủ định và câu nghi vấn với danh từ không đếm được.",
  },
  {
    id: 13,
    unit: "Grammar Review",
    question: "My brother ______ to school every morning.",
    options: ["walk", "walks", "walking", "is walking"],
    correctAnswer: 1,
    explanation: "Thì Hiện tại đơn với chủ ngữ ngôi thứ 3 số ít 'My brother' thì động từ thêm 's/es'.",
  },
  {
    id: 14,
    unit: "Vocabulary Review",
    question: "I often ______ photos with my new camera.",
    options: ["do", "make", "take", "get"],
    correctAnswer: 2,
    explanation: "Cụm từ cố định: 'take photos' (chụp ảnh).",
  },
  {
    id: 15,
    unit: "Unit 2: My House",
    question: "Where is the cat? It's ______ the sofa.",
    options: ["in", "on", "at", "between"],
    correctAnswer: 1,
    explanation: "'On the sofa' (trên ghế sofa).",
  },
  {
    id: 16,
    unit: "Unit 3: My Friends",
    question: "Look! The students ______ flowers in the garden.",
    options: ["plant", "plants", "are planting", "is planting"],
    correctAnswer: 2,
    explanation: "Dấu hiệu 'Look!' cho thấy hành động đang xảy ra, dùng thì Hiện tại tiếp diễn.",
  },
  {
    id: 17,
    unit: "Unit 4: My Neighbourhood",
    question: "Is your house ______ than her house?",
    options: ["big", "bigger", "biggest", "more big"],
    correctAnswer: 1,
    explanation: "So sánh hơn của tính từ ngắn 'big' là 'bigger' (gấp đôi phụ âm cuối).",
  },
  {
    id: 18,
    unit: "Unit 5: Natural Wonders",
    question: "What is the ______ natural wonder in the world?",
    options: ["great", "greater", "greatest", "most great"],
    correctAnswer: 2,
    explanation: "Cấu trúc so sánh nhất: 'the + greatest'.",
  },
  {
    id: 19,
    unit: "Unit 6: Our Tet Holiday",
    question: "People ______ throw rubbish in the street.",
    options: ["should", "shouldn't", "must", "can"],
    correctAnswer: 1,
    explanation: "Lời khuyên: 'shouldn't' (không nên) vứt rác bừa bãi.",
  },
  {
    id: 20,
    unit: "General Review",
    question: "I ______ going to the cinema with my friends.",
    options: ["like", "likes", "am liking", "to like"],
    correctAnswer: 0,
    explanation: "Động từ chỉ sở thích 'like' thường dùng ở thì Hiện tại đơn.",
  },
];
